import * as React from 'react'
import { storiesOf } from '@storybook/react'
import * as Icons from "./Icons"
import * as IconsM from "./materialinear"

import { getRootContainer } from '../../../Common/stories';
import { withKnobs, text, boolean, number } from '@storybook/addon-knobs';

const alertFont = { fontSize: "36px", color: "green", }

const stories = storiesOf('Components|Display/UpIcons', module);

stories.addDecorator(withKnobs)
stories.addDecorator(getRootContainer('UpIcons'));

stories.add('materialinear',
    () => (
        <div style={{ padding: "16px" }} >

            <IconsM.Exclam />
            <IconsM.Quotedbl />
            <IconsM.Numbersign />
            <IconsM.Dollar />
            <IconsM.Percent />
            <IconsM.Ampersand />
            <IconsM.Quotesingle />
            <IconsM.Parenleft />
            <IconsM.Parenright />
            <IconsM.Asterisk />
            <IconsM.Plus />
            <IconsM.Comma />
            <IconsM.Hyphen />
            <IconsM.Period />
            <IconsM.Slash />
            <IconsM.Zero />
            <IconsM.One />
            <IconsM.Two />
            <IconsM.Three />
            <IconsM.Four />
            <IconsM.Five />
            <IconsM.Six />
            <IconsM.Seven />
            <IconsM.Eight />
            <IconsM.Nine />
            <IconsM.Colon />
            <IconsM.Semicolon />
            <IconsM.Less />
            <IconsM.Equal />
            <IconsM.Greater />
            <IconsM.Question />
            <IconsM.At />
            <IconsM.A />
            <IconsM.B />
            <IconsM.C />
            <IconsM.D />
            <IconsM.E />
            <IconsM.F />
            <IconsM.G />
            <IconsM.H />
            <IconsM.I />
            <IconsM.J />
            <IconsM.K />
            <IconsM.L />
            <IconsM.M />
            <IconsM.N />
            <IconsM.O />
            <IconsM.P />
            <IconsM.Q />
            <IconsM.R />
            <IconsM.S />
            <IconsM.T />
            <IconsM.U />
            <IconsM.V />
            <IconsM.W />
            <IconsM.X />
            <IconsM.Y />
            <IconsM.Z />
            <IconsM.Bracketleft />
            <IconsM.Backslash />
            <IconsM.Bracketright />
            <IconsM.Asciicircum />
            <IconsM.Underscore />
            <IconsM.Grave />
            <IconsM.a />
            <IconsM.b />
            <IconsM.c />
            <IconsM.d />
            <IconsM.e />
            <IconsM.f />
            <IconsM.g />
            <IconsM.h />
            <IconsM.i />
            <IconsM.j />
            <IconsM.k />
            <IconsM.l />
            <IconsM.m />
            <IconsM.n />
            <IconsM.o />
            <IconsM.p />
            <IconsM.q />
            <IconsM.r />
            <IconsM.s />
            <IconsM.t />
            <IconsM.u />
            <IconsM.v />
            <IconsM.w />
            <IconsM.x />
            <IconsM.y />
            <IconsM.z />
            <IconsM.Braceleft />
            <IconsM.Bar />
            <IconsM.Braceright />
            <IconsM.Asciitilde />
            <IconsM.Copyright />
            <IconsM.Lhome />
            <IconsM.Lhome2 />
            <IconsM.Lhome3 />
            <IconsM.Lhome4 />
            <IconsM.Lhome5 />
            <IconsM.Lhome6 />
            <IconsM.Lbathtub />
            <IconsM.Ltoothbrush />
            <IconsM.Lbed />
            <IconsM.Lcouch />
            <IconsM.Lchair />
            <IconsM.Lcity />
            <IconsM.Lapartment />
            <IconsM.Lpencil />
            <IconsM.Lpencil2 />
            <IconsM.Lpen />
            <IconsM.Lpencil3 />
            <IconsM.Leraser />
            <IconsM.Lpencil4 />
            <IconsM.Lpencil5 />
            <IconsM.Lfeather />
            <IconsM.Lfeather2 />
            <IconsM.Lfeather3 />
            <IconsM.Lpen2 />
            <IconsM.LpenAdd />
            <IconsM.LpenRemove />
            <IconsM.Lvector />
            <IconsM.Lpen3 />
            <IconsM.Lblog />
            <IconsM.Lbrush />
            <IconsM.Lbrush2 />
            <IconsM.Lspray />
            <IconsM.LpaintRoller />
            <IconsM.Lstamp />
            <IconsM.Ltape />
            <IconsM.LdeskTape />
            <IconsM.Ltexture />
            <IconsM.LcolorPicker />
            <IconsM.Lpalette />
            <IconsM.LcolorSampler />
            <IconsM.Lbucket />
            <IconsM.Lgradient />
            <IconsM.Lgradient2 />
            <IconsM.LmagicWand />
            <IconsM.Lmagnet />
            <IconsM.LpencilRuler />
            <IconsM.LpencilRuler2 />
            <IconsM.Lcompass />
            <IconsM.Ltarget />
            <IconsM.Lgun />
            <IconsM.Lbottle />
            <IconsM.Ldrop />
            <IconsM.LdropCrossed />
            <IconsM.Ldrop2 />
            <IconsM.Lsnow />
            <IconsM.Lsnow2 />
            <IconsM.Lfire />
            <IconsM.Llighter />
            <IconsM.Lknife />
            <IconsM.Ldagger />
            <IconsM.Ltissue />
            <IconsM.LtoiletPaper />
            <IconsM.Lpoop />
            <IconsM.Lumbrella />
            <IconsM.Lumbrella2 />
            <IconsM.Lrain3 />
            <IconsM.Ltornado />
            <IconsM.Lwind />
            <IconsM.Lcooling />
            <IconsM.Lcontrast />
            <IconsM.LsunSmall />
            <IconsM.Lsun />
            <IconsM.Lsun2 />
            <IconsM.Lmoon />
            <IconsM.Lcloud />
            <IconsM.LcloudUpload />
            <IconsM.LcloudDowload />
            <IconsM.LcloudRain />
            <IconsM.LcloudHailstones />
            <IconsM.LcloudSnow />
            <IconsM.LcloudWind />
            <IconsM.LsunWind />
            <IconsM.CloudFog />
            <IconsM.LcloudSun />
            <IconsM.LcloudLightning />
            <IconsM.LcloudSync />
            <IconsM.LcloudLock />
            <IconsM.LcloudGear />
            <IconsM.LcloudAlert />
            <IconsM.LcloudCheck />
            <IconsM.LcloudCross />
            <IconsM.LcloudCrossed />
            <IconsM.LcloudDatabase />
            <IconsM.Ldatabase />
            <IconsM.LdatabaseAdd />
            <IconsM.LdatabaseRemove />
            <IconsM.LdatabaseLock />
            <IconsM.LdatabaseRefresh />
            <IconsM.LdatabaseCheck />
            <IconsM.LdatabaseHistory />
            <IconsM.LdatabaseUpload />
            <IconsM.LdatabaseDownload />
            <IconsM.Lserver />
            <IconsM.Lshield />
            <IconsM.LshieldCheck />
            <IconsM.LshieldAlert />
            <IconsM.LshieldCross />
            <IconsM.Llock />
            <IconsM.LrotationLock />
            <IconsM.Lunlock />
            <IconsM.Lkey />
            <IconsM.LkeyHole />
            <IconsM.LtoggleOff />
            <IconsM.LtoggleOn />
            <IconsM.Lcog />
            <IconsM.Lcog2 />
            <IconsM.Ltool />
            <IconsM.Ltool1 />
            <IconsM.Ltool3 />
            <IconsM.Ltool4 />
            <IconsM.Ltool5 />
            <IconsM.Ltool6 />
            <IconsM.Ltool7 />
            <IconsM.Ltoole8 />
            <IconsM.Ltool9 />
            <IconsM.Lfactory />
            <IconsM.Lfactory2 />
            <IconsM.Lrecycle />
            <IconsM.Ltrash />
            <IconsM.Ltrash2 />
            <IconsM.Ltrash3 />
            <IconsM.Lbroom />
            <IconsM.Lgame />
            <IconsM.Lgamepad />
            <IconsM.Ljoystick />
            <IconsM.Ldice />
            <IconsM.Lspades />
            <IconsM.Ldiamonds />
            <IconsM.Lclubs />
            <IconsM.Lhearts />
            <IconsM.Lheart />
            <IconsM.Lstar />
            <IconsM.LstarHalf />
            <IconsM.LstarEmpty />
            <IconsM.Lflag />
            <IconsM.Lflag2 />
            <IconsM.Lflag3 />
            <IconsM.LmailboxFull />
            <IconsM.LmailboxEmpty />
            <IconsM.LatSign />
            <IconsM.Lenvelope />
            <IconsM.LenvelopeOpen />
            <IconsM.Lpaperclip />
            <IconsM.LpaperPlane />
            <IconsM.Lreply />
            <IconsM.LreplyAll />
            <IconsM.Linbox />
            <IconsM.Linbox2 />
            <IconsM.Loutbox />
            <IconsM.Lbox />
            <IconsM.Larchive />
            <IconsM.Larchive2 />
            <IconsM.Ldrawers />
            <IconsM.Ldrawers2 />
            <IconsM.Ldrawers3 />
            <IconsM.Leye />
            <IconsM.LeyeCrossed />
            <IconsM.LeyesPlus />
            <IconsM.LeyeMinus />
            <IconsM.Lbinoclars />
            <IconsM.Lbinoclars2 />
            <IconsM.Lhdd />
            <IconsM.LhddDown />
            <IconsM.LhddUp />
            <IconsM.LfloppyDisk />
            <IconsM.Ldisc />
            <IconsM.Ltape2 />
            <IconsM.Lprinter />
            <IconsM.Lshredder />
            <IconsM.LfileEmpty />
            <IconsM.LfileAdd />
            <IconsM.LfileCheck />
            <IconsM.LfileLock />
            <IconsM.Lfiles />
            <IconsM.Lcopy />
            <IconsM.Lcompare />
            <IconsM.Lfolder />
            <IconsM.LfolderSearch />
            <IconsM.LfolderPlus />
            <IconsM.LfolderMinus />
            <IconsM.LfolderDownload />
            <IconsM.LfolderUpload />
            <IconsM.LfolderStar />
            <IconsM.LfolderHeart />
            <IconsM.LfolderUser />
            <IconsM.LfolderShared />
            <IconsM.LfolderMusic />
            <IconsM.LfolderPicture />
            <IconsM.LfolderFilm />
            <IconsM.Lscissors />
            <IconsM.Lpaste />
            <IconsM.LclipboardEmpty />
            <IconsM.LclipboardPencil />
            <IconsM.LclipboardText />
            <IconsM.LclipboardCheck />
            <IconsM.LclipboardDown />
            <IconsM.LclipboardLeft />
            <IconsM.LclipboardAlert />
            <IconsM.LclipboardUser />
            <IconsM.Lregister />
            <IconsM.Lenter />
            <IconsM.Lexit />
            <IconsM.Lpapers />
            <IconsM.Lnews />
            <IconsM.Lreading />
            <IconsM.Ltypewriter />
            <IconsM.Ldocument />
            <IconsM.Ldocument2 />
            <IconsM.LgraduationHat />
            <IconsM.Llicense />
            <IconsM.Llicense2 />
            <IconsM.LmedalEmpty />
            <IconsM.LmedalFirst />
            <IconsM.LmedalSecond />
            <IconsM.LmedalThird />
            <IconsM.Lpodium />
            <IconsM.Ltrophy />
            <IconsM.Ltrophy2 />
            <IconsM.LmusicNote />
            <IconsM.LmusicNote2 />
            <IconsM.LmusicNote3 />
            <IconsM.Lplaylist />
            <IconsM.LplaylistAdd />
            <IconsM.Lguitar />
            <IconsM.Ltrumpet />
            <IconsM.Lalbum />
            <IconsM.Lshuffle />
            <IconsM.LrepeatOne />
            <IconsM.Lrepeat />
            <IconsM.Lheadphones />
            <IconsM.Lheadset />
            <IconsM.Lloudspeacker />
            <IconsM.Lequalizer />
            <IconsM.Ltheater />
            <IconsM.L3dGlasses />
            <IconsM.Lticket />
            <IconsM.Lpresentation />
            <IconsM.Lplay />
            <IconsM.LfilmPlay />
            <IconsM.LclapboardPlay />
            <IconsM.Lmedia />
            <IconsM.Lfilm />
            <IconsM.Lfilm2 />
            <IconsM.Lsurveillance />
            <IconsM.Lsurveillance2 />
            <IconsM.Lcamera />
            <IconsM.LcameraCrossed />
            <IconsM.LcameraPlay />
            <IconsM.LtimeLapse />
            <IconsM.Lrecord />
            <IconsM.Lcamera2 />
            <IconsM.LcameraFilp />
            <IconsM.Lpanorama />
            <IconsM.LtimeLapse2 />
            <IconsM.Lshutter />
            <IconsM.Lshutter2 />
            <IconsM.LfaceDetection />
            <IconsM.Lflare />
            <IconsM.Lconvex />
            <IconsM.Lconcave />
            <IconsM.Lpicture />
            <IconsM.Lpicture2 />
            <IconsM.Lpicture3 />
            <IconsM.Lpictures />
            <IconsM.Lbook />
            <IconsM.LaudioBook />
            <IconsM.Lbook2 />
            <IconsM.Lbookmark />
            <IconsM.Lbookmark2 />
            <IconsM.Lbookmark3 />
            <IconsM.Llibrary />
            <IconsM.Llibrary2 />
            <IconsM.Lcontacts />
            <IconsM.Lprofile />
            <IconsM.Lportrait />
            <IconsM.Lportrait2 />
            <IconsM.Luser />
            <IconsM.LuserAdd />
            <IconsM.LuserMinus />
            <IconsM.LuserLock />
            <IconsM.Lusers />
            <IconsM.Lusers2 />
            <IconsM.LusersAdd />
            <IconsM.LusersMinus />
            <IconsM.LgroupWork />
            <IconsM.Lwoman />
            <IconsM.Lman />
            <IconsM.Lbaby />
            <IconsM.Lbaby2 />
            <IconsM.Lbaby3 />
            <IconsM.LbabyBottle />
            <IconsM.Lwalk />
            <IconsM.LhandWaving />
            <IconsM.Ljump />
            <IconsM.Lrun />
            <IconsM.Lwoman2 />
            <IconsM.Lman2 />
            <IconsM.LmanWoman />
            <IconsM.Lheight />
            <IconsM.Lweight />
            <IconsM.Lscale2 />
            <IconsM.Lbutton />
            <IconsM.LbowTie />
            <IconsM.Ltie />
            <IconsM.Lsocks />
            <IconsM.Lshoe />
            <IconsM.Lshoes />
            <IconsM.Lhat />
            <IconsM.Lpants />
            <IconsM.Lshorts />
            <IconsM.LflipFlop />
            <IconsM.Lshirt />
            <IconsM.Lhanger />
            <IconsM.Llaundry />
            <IconsM.Lstore />
            <IconsM.Lhaircut />
            <IconsM.Lstore24 />
            <IconsM.Lbarcode />
            <IconsM.Lbarcode2 />
            <IconsM.Lbarcode3 />
            <IconsM.Lcashier />
            <IconsM.Lbag />
            <IconsM.Lbag2 />
            <IconsM.Lcart />
            <IconsM.LcartEmpty />
            <IconsM.LcartFull />
            <IconsM.LcartPlus />
            <IconsM.LcartPlus2 />
            <IconsM.LcartAdd />
            <IconsM.LcartRemove />
            <IconsM.LcartExchange />
            <IconsM.Ltag />
            <IconsM.Ltags />
            <IconsM.Lreceipt />
            <IconsM.Lwallet />
            <IconsM.LcreditCard />
            <IconsM.LcashDollar />
            <IconsM.LcashEuro />
            <IconsM.LcashPound />
            <IconsM.LcashYen />
            <IconsM.LbagDollar />
            <IconsM.LbagEuro />
            <IconsM.LbagPound />
            <IconsM.LbagYen />
            <IconsM.LcoinDollar />
            <IconsM.LcoinEurp />
            <IconsM.LcoinPound />
            <IconsM.LcoinYen />
            <IconsM.Lcalculator />
            <IconsM.Lcalculator2 />
            <IconsM.Labacus />
            <IconsM.Lvault />
            <IconsM.Ltelephone />
            <IconsM.LphoneLock />
            <IconsM.LphoneWave />
            <IconsM.LphonePause />
            <IconsM.LphoneOugoing />
            <IconsM.LphoneIncoming />
            <IconsM.LphoneInOut />
            <IconsM.LphoneError />
            <IconsM.LphoneSip />
            <IconsM.LphonePlus />
            <IconsM.LphoneMinus />
            <IconsM.Lvoicemail />
            <IconsM.Ldial />
            <IconsM.Ltelephone2 />
            <IconsM.Lpin />
            <IconsM.Lpin2 />
            <IconsM.LmapMarker />
            <IconsM.LmapMarkerUser />
            <IconsM.LmapMarkerDown />
            <IconsM.LmapMarkerCheck />
            <IconsM.LmapMarkerCrossed />
            <IconsM.Lradar />
            <IconsM.Lcompass2 />
            <IconsM.Lmap />
            <IconsM.Lmap2 />
            <IconsM.Llocation />
            <IconsM.LroadSign />
            <IconsM.LcalendarEmpty />
            <IconsM.LcalendarCheck />
            <IconsM.LcalendarCross />
            <IconsM.Lcalendar31 />
            <IconsM.LcalendarFull />
            <IconsM.LcalendarInsert />
            <IconsM.LcalendarText />
            <IconsM.LcalendarUser />
            <IconsM.Lmouse />
            <IconsM.LmouseLeft />
            <IconsM.LmouseRight />
            <IconsM.LmouseBoth />
            <IconsM.Lkeyboard />
            <IconsM.LkeyboardUp />
            <IconsM.LkeyboardDown />
            <IconsM.UniE794 />
            <IconsM.SpellCheck />
            <IconsM.Lescape />
            <IconsM.Lenter2 />
            <IconsM.Lscreen />
            <IconsM.LaspectRatio />
            <IconsM.Lsignal />
            <IconsM.LsignalLock />
            <IconsM.Lsignal80 />
            <IconsM.Lsignal60 />
            <IconsM.Lsignal40 />
            <IconsM.Lsignal20 />
            <IconsM.Lsignal0 />
            <IconsM.LsignalBlocked />
            <IconsM.Lsim />
            <IconsM.LflashMemory />
            <IconsM.LusbDrive />
            <IconsM.Lmobile />
            <IconsM.Lmobile2 />
            <IconsM.LmobileNotification />
            <IconsM.LmobileVibrator />
            <IconsM.LmobileEmbed />
            <IconsM.LmobileWave />
            <IconsM.Ltablet />
            <IconsM.Ltablet2 />
            <IconsM.Llaptop />
            <IconsM.LlaptopPhone />
            <IconsM.Ldesktop />
            <IconsM.Llaunch />
            <IconsM.LnewTab />
            <IconsM.Lwindow />
            <IconsM.Lcable />
            <IconsM.Lcable2 />
            <IconsM.Ltv />
            <IconsM.Lradio />
            <IconsM.Lremote />
            <IconsM.LpowerSwitch />
            <IconsM.Lpower />
            <IconsM.LpowerCrossed />
            <IconsM.LflashAuto />
            <IconsM.Llamp />
            <IconsM.Lflashlight />
            <IconsM.Llampshade />
            <IconsM.Lcord />
            <IconsM.Loutlet />
            <IconsM.LbatteryPower />
            <IconsM.LbatteryEmpty />
            <IconsM.LbatteryAlert />
            <IconsM.LbatteryError />
            <IconsM.LbatteryLow1 />
            <IconsM.LbatteryLow2 />
            <IconsM.LbatteryLow3 />
            <IconsM.LbatteryMid1 />
            <IconsM.LbatteryMid2 />
            <IconsM.LbatteryMid3 />
            <IconsM.LbatteryFull />
            <IconsM.LbatteryCharging />
            <IconsM.LbatteryCharging2 />
            <IconsM.LbatteryCharging3 />
            <IconsM.LbatteryCharging4 />
            <IconsM.LbatteryCharging5 />
            <IconsM.UniE7D1LbatteryCharging6 />
            <IconsM.LbatteryCharging7 />
            <IconsM.Lchip />
            <IconsM.LchipX64 />
            <IconsM.LchipX86 />
            <IconsM.Lbubble />
            <IconsM.Lbubbles />
            <IconsM.LbubbleDots />
            <IconsM.LbubbleAlert />
            <IconsM.LbubbleQuestion />
            <IconsM.LbubbleText />
            <IconsM.UniE7DCLbubblePencil />
            <IconsM.LbubblePicture />
            <IconsM.LbubbleVideo />
            <IconsM.LbubbleUser />
            <IconsM.LbubbleQuote />
            <IconsM.LbubbleHeart />
            <IconsM.LbubbleEmoticon />
            <IconsM.LbubbleAttachment />
            <IconsM.LphoneBubble />
            <IconsM.LquotteOpen />
            <IconsM.LquotteClose />
            <IconsM.Ldna />
            <IconsM.LheartPulse />
            <IconsM.Lpulse />
            <IconsM.Lsyringe />
            <IconsM.Lpills />
            <IconsM.LfirstAid />
            <IconsM.Lhelp />
            <IconsM.Lbandage />
            <IconsM.Lbandages />
            <IconsM.Lthermometer />
            <IconsM.Lmicroscope />
            <IconsM.Lbrain />
            <IconsM.Lbeaker />
            <IconsM.Lskull />
            <IconsM.Lbone />
            <IconsM.Lconstruction />
            <IconsM.Lconstruction2 />
            <IconsM.LpieChart />
            <IconsM.LpieChart2 />
            <IconsM.Lgraph />
            <IconsM.LchartGrowth />
            <IconsM.LchartBars />
            <IconsM.LchartSettings />
            <IconsM.Lcake />
            <IconsM.Lgift />
            <IconsM.Lballoon />
            <IconsM.Lrank />
            <IconsM.Lrank2 />
            <IconsM.Lrank3 />
            <IconsM.Lcrown />
            <IconsM.Llotus />
            <IconsM.Ldiamond />
            <IconsM.Ldiamond2 />
            <IconsM.Ldiamond3 />
            <IconsM.Ldiamond4 />
            <IconsM.Lteacup />
            <IconsM.Lteapot />
            <IconsM.Lglass />
            <IconsM.Lbottle1 />
            <IconsM.Lglass2 />
            <IconsM.Lglass3 />
            <IconsM.Ldinner />
            <IconsM.Ldinner2 />
            <IconsM.Lchef />
            <IconsM.Lscale3 />
            <IconsM.Legg />
            <IconsM.Legg2 />
            <IconsM.Leggs />
            <IconsM.Lplatter />
            <IconsM.Lsteak />
            <IconsM.Lhamburger />
            <IconsM.Lhotdog />
            <IconsM.Lpizza />
            <IconsM.Lsausage />
            <IconsM.Lchicken />
            <IconsM.Lfish />
            <IconsM.Lcarrot />
            <IconsM.Lcheese />
            <IconsM.Lbread />
            <IconsM.LiceCream />
            <IconsM.LiceCream2 />
            <IconsM.Lcandy />
            <IconsM.Llollipop />
            <IconsM.LcoffeBean />
            <IconsM.LcoffeCup />
            <IconsM.Lcherry />
            <IconsM.Lgrapes />
            <IconsM.Lcitrus />
            <IconsM.Lapple />
            <IconsM.Lleaf />
            <IconsM.Llandscape />
            <IconsM.LpineTree />
            <IconsM.Ltree />
            <IconsM.Lcastus />
            <IconsM.Lpaw />
            <IconsM.Lfootprint />
            <IconsM.LspeedSlow />
            <IconsM.LspeedMedium />
            <IconsM.LspeedFast />
            <IconsM.Lrocket />
            <IconsM.Ljustice />
            <IconsM.Ljustice2 />
            <IconsM.Lsuitcase />
            <IconsM.LluggageWeight />
            <IconsM.Ldolly />
            <IconsM.Lplane />
            <IconsM.LplaneCrossed />
            <IconsM.Lhelicopter />
            <IconsM.LtrafficLights />
            <IconsM.Lsiren />
            <IconsM.Lroad />
            <IconsM.Lengine />
            <IconsM.LoilPressure />
            <IconsM.LcoolantTemperature />
            <IconsM.LcarBattery />
            <IconsM.Lgas />
            <IconsM.Lgallon />
            <IconsM.Ltransmission />
            <IconsM.Lcar />
            <IconsM.LcarWash />
            <IconsM.LcarWash2 />
            <IconsM.Lbus />
            <IconsM.Lbus2 />
            <IconsM.Lcar1 />
            <IconsM.Lparking />
            <IconsM.LcarLock />
            <IconsM.Ltaxi />
            <IconsM.LcarSiren />
            <IconsM.LcarWash3 />
            <IconsM.LcarWash4 />
            <IconsM.Lambulance />
            <IconsM.Ltruck />
            <IconsM.Ltruck2 />
            <IconsM.LtruckWeight />
            <IconsM.Ltrain />
            <IconsM.Lboat />
            <IconsM.Lboat2 />
            <IconsM.Lanchor />
            <IconsM.UniE85E />
            <IconsM.Lbicycle />
            <IconsM.Lbicycle2 />
            <IconsM.Lexercise />
            <IconsM.Lexercise2 />
            <IconsM.Lswim />
            <IconsM.Lfootball />
            <IconsM.Lbaseball />
            <IconsM.Lbaseball2 />
            <IconsM.Ltennis />
            <IconsM.Ltennis2 />
            <IconsM.LpingPong />
            <IconsM.Lhockey />
            <IconsM.L8ball />
            <IconsM.Lbowling />
            <IconsM.Lbowling2 />
            <IconsM.Lgolf />
            <IconsM.Lgolf2 />
            <IconsM.Larchery />
            <IconsM.Lslingshot />
            <IconsM.Lsoccer />
            <IconsM.Lbasketball />
            <IconsM.Lcube />
            <IconsM.L3dRotate />
            <IconsM.Lpuzzle />
            <IconsM.Lglasses />
            <IconsM.Lglasses2 />
            <IconsM.Laccessibility />
            <IconsM.Laccessibility2 />
            <IconsM.Lwall />
            <IconsM.Lfence />
            <IconsM.Lwall2 />
            <IconsM.Lgrid />
            <IconsM.LresizeHandle />
            <IconsM.Lgrid2 />
            <IconsM.Lselect />
            <IconsM.Lselect2 />
            <IconsM.LsiteMap />
            <IconsM.Learth />
            <IconsM.LearthLock />
            <IconsM.Lnetwork />
            <IconsM.LnetworkLock />
            <IconsM.Lplanet />
            <IconsM.Lemoticone1 />
            <IconsM.Lemoticone2 />
            <IconsM.Lemoticone3 />
            <IconsM.Lemoticone4 />
            <IconsM.Lemoticone5 />
            <IconsM.Lemoticone6 />
            <IconsM.Lemoticone7 />
            <IconsM.Lemoticone8 />
            <IconsM.Lemoticone9 />
            <IconsM.Lemoticone10 />
            <IconsM.Lemoticone11 />
            <IconsM.Lemoticone12 />
            <IconsM.Lemoticone13 />
            <IconsM.Lemoticone14 />
            <IconsM.Lemoticone15 />
            <IconsM.Lemoticone16 />
            <IconsM.Lemoticone17 />
            <IconsM.Lemoticone18 />
            <IconsM.Lemoticone19 />
            <IconsM.Lemoticone20 />
            <IconsM.Lemoticone21 />
            <IconsM.Lemoticone22 />
            <IconsM.Lemoticone23 />
            <IconsM.Lghost />
            <IconsM.Lghost2 />
            <IconsM.Lhalloween />
            <IconsM.Lchristmas />
            <IconsM.Leaster />
            <IconsM.Lmustache />
            <IconsM.Lmustache2 />
            <IconsM.Lpipe />
            <IconsM.Lbell />
            <IconsM.LalarmAdd />
            <IconsM.LalarmSnooze />
            <IconsM.LalarmRinging />
            <IconsM.Lmegaphone />
            <IconsM.Lhearing />
            <IconsM.LvolumeHight />
            <IconsM.LvolumeMiddle />
            <IconsM.LvolumeLow />
            <IconsM.Lvolume />
            <IconsM.Lmute />
            <IconsM.Llan />
            <IconsM.Llan2 />
            <IconsM.Lwifi />
            <IconsM.LwifiLock />
            <IconsM.LwifiBlocked />
            <IconsM.LwifiMid />
            <IconsM.LwifiLow />
            <IconsM.LwifiLow2 />
            <IconsM.LwifiAlert />
            <IconsM.LwifiAlert2 />
            <IconsM.LwifiAlert3 />
            <IconsM.LwifiAlert4 />
            <IconsM.Lstream />
            <IconsM.LstreamCheck />
            <IconsM.LstreamError />
            <IconsM.LstreamAlert />
            <IconsM.Lcommunication />
            <IconsM.LcommunicationCrossed />
            <IconsM.Lwaves />
            <IconsM.Lwaves2 />
            <IconsM.Lsatellite />
            <IconsM.Lsatellite2 />
            <IconsM.Lmic />
            <IconsM.LmicMute />
            <IconsM.Lmic2 />
            <IconsM.Lspotlight />
            <IconsM.Lloading />
            <IconsM.Lloadinge />
            <IconsM.Lloading3 />
            <IconsM.Lloading4 />
            <IconsM.Lrefresh />
            <IconsM.Lrefresh2 />
            <IconsM.Lundo />
            <IconsM.Lredo />
            <IconsM.Ljump2 />
            <IconsM.Lundo2 />
            <IconsM.Lredo2 />
            <IconsM.Lsync />
            <IconsM.LrepeatOne2 />
            <IconsM.LsyncCrossed />
            <IconsM.Lsync2 />
            <IconsM.LrepeatOne3 />
            <IconsM.LsyncCrossed2 />
            <IconsM.Lreturn />
            <IconsM.Lreturn2 />
            <IconsM.Lrefund />
            <IconsM.Lhistory />
            <IconsM.Lhistory2 />
            <IconsM.Lhistory3 />
            <IconsM.Lclock />
            <IconsM.Lclock2 />
            <IconsM.Lclock3 />
            <IconsM.Lwatch />
            <IconsM.Lalarm3 />
            <IconsM.LalarmAdd2 />
            <IconsM.LalarmRemove2 />
            <IconsM.LalarmCheck />
            <IconsM.LalarmError />
            <IconsM.Ltimer />
            <IconsM.LtimerCrossed />
            <IconsM.Ltimer2 />
            <IconsM.LtimerCrossed2 />
            <IconsM.Ldownload />
            <IconsM.Lupload />
            <IconsM.Ldownload2 />
            <IconsM.Lupload2 />
            <IconsM.LenterUp />
            <IconsM.LenterDown />
            <IconsM.LenterLeft />
            <IconsM.LenterRight />
            <IconsM.LexitUp />
            <IconsM.LexitDown />
            <IconsM.LexitLeft />
            <IconsM.LexitRight />
            <IconsM.LenterUp2 />
            <IconsM.LenterDown2 />
            <IconsM.LenterVertical />
            <IconsM.LenterLeft2 />
            <IconsM.LenterRight2 />
            <IconsM.LenterHorizontal />
            <IconsM.LexitUp2 />
            <IconsM.LexitDown2 />
            <IconsM.LexitLeft2 />
            <IconsM.LexitRight2 />
            <IconsM.Lcli />
            <IconsM.Lbug />
            <IconsM.Lcode />
            <IconsM.LfileCode />
            <IconsM.LfileImage />
            <IconsM.LfileZip />
            <IconsM.LfileAudio />
            <IconsM.LfileVideo />
            <IconsM.LfilePreview />
            <IconsM.LfileCharts />
            <IconsM.LfileStats />
            <IconsM.LfileSpreadsheet />
            <IconsM.Llink />
            <IconsM.Lunlink />
            <IconsM.Llink2 />
            <IconsM.Lunlink2 />
            <IconsM.LthumbsUp />
            <IconsM.LthumbsDown />
            <IconsM.LthumbsUp2 />
            <IconsM.UniE91CLthumbsDown2 />
            <IconsM.UniE91DLthumbsUp3 />
            <IconsM.LthumbsDown3 />
            <IconsM.Lshare2 />
            <IconsM.Lshare3 />
            <IconsM.Lshare4 />
            <IconsM.Lsearch />
            <IconsM.LfileSearch />
            <IconsM.LfindReplace />
            <IconsM.LzoomIn />
            <IconsM.LzoomOut />
            <IconsM.Lloupe />
            <IconsM.LloupeZoomIn />
            <IconsM.LloupeZoomOut />
            <IconsM.Lcancel />
            <IconsM.Lmenu />
            <IconsM.Llist />
            <IconsM.Llist2 />
            <IconsM.Llist3 />
            <IconsM.Llist4 />
            <IconsM.Llist5 />
            <IconsM.Lmenu2 />
            <IconsM.Lexclamation />
            <IconsM.Lquestion />
            <IconsM.Lcheck />
            <IconsM.Lcross />
            <IconsM.Lplus />
            <IconsM.Lminus />
            <IconsM.Lpercent />
            <IconsM.LchevronUp />
            <IconsM.LchevronDown />
            <IconsM.LchevronLeft />
            <IconsM.LchevronRight />
            <IconsM.LchevronsExpandVertical />
            <IconsM.LchevronsExpandHorizontal />
            <IconsM.LchevronsContractVertical />
            <IconsM.LchevronsContractHorizontal />
            <IconsM.LarrowUp />
            <IconsM.LarrowDown />
            <IconsM.LarrowLeft />
            <IconsM.LarrowRight />
            <IconsM.LarrowUpRight />
            <IconsM.LarrowMerge />
            <IconsM.LarrowSplit />
            <IconsM.LarrowDivert />
            <IconsM.LarrowReturn />
            <IconsM.Lexpand />
            <IconsM.Lcontract />
            <IconsM.Lexpand2 />
            <IconsM.Lcontract2 />
            <IconsM.Lmove />
            <IconsM.Ltab />
            <IconsM.LarrowWave />
            <IconsM.Lexpand3 />
            <IconsM.Lexpand4 />
            <IconsM.Lcontract3 />
            <IconsM.Lnotification />
            <IconsM.Lwarning />
            <IconsM.LnotificationCircle />
            <IconsM.LquestionCircle />
            <IconsM.LmenuCircle />
            <IconsM.LcheckCircle />
            <IconsM.LcrossCircle />
            <IconsM.LplusCircle />
            <IconsM.LminusCircle />
            <IconsM.LpercentCircle />
            <IconsM.LarrowUpCircle />
            <IconsM.LarrowDownCircle />
            <IconsM.LarrowLeftCircle />
            <IconsM.LarrowRightCircle />
            <IconsM.LchevronUpCircle />
            <IconsM.LchevronDownCircle />
            <IconsM.LchevronLeftCircle />
            <IconsM.LchevronRightCircle />
            <IconsM.LbackwardCircle />
            <IconsM.LfirstCircle />
            <IconsM.LpreviousCircle />
            <IconsM.LstopCircle />
            <IconsM.LplayCircle />
            <IconsM.Lpause />
            <IconsM.LnextCircle />
            <IconsM.LlastCircle />
            <IconsM.LforwardCircle />
            <IconsM.LejectCircle />
            <IconsM.Lcrop />
            <IconsM.LframeExpand />
            <IconsM.LframeContract />
            <IconsM.Lfocus />
            <IconsM.Ltransform />
            <IconsM.Lgrid3 />
            <IconsM.LgridCrossed />
            <IconsM.Llayers />
            <IconsM.LlayersCrossed />
            <IconsM.Lfold />
            <IconsM.Lrulers />
            <IconsM.Lruler />
            <IconsM.Lfunnel />
            <IconsM.Lmirror1 />
            <IconsM.Lmirror2 />
            <IconsM.Lflip1 />
            <IconsM.Lfli2 />
            <IconsM.Langle />
            <IconsM.Langle2 />
            <IconsM.Lsubstract />
            <IconsM.Lunion />
            <IconsM.Lintersect />
            <IconsM.Lexclude />
            <IconsM.LalignCenterVertical />
            <IconsM.LalignRight />
            <IconsM.LalignBottom />
            <IconsM.LalignLeft />
            <IconsM.LalignCenterHorizontal />
            <IconsM.LalignTop />
            <IconsM.Lquare />
            <IconsM.LplusSquare />
            <IconsM.LminusSquare />
            <IconsM.LpercentSquare />
            <IconsM.LarrowUpSquare />
            <IconsM.LarrowDownSquare />
            <IconsM.LarrowLeftSquare />
            <IconsM.LarrowRightSquare />
            <IconsM.LchevronUpSquare />
            <IconsM.LchevronDownSquare />
            <IconsM.LchevronLeftSquare />
            <IconsM.LchevronRightSquare />
            <IconsM.LcheckSquare />
            <IconsM.LcrossSquare />
            <IconsM.LmenuSquare />
            <IconsM.Lforbiden />
            <IconsM.Lcircle />
            <IconsM.LradioButton />
            <IconsM.Lligature />
            <IconsM.LtextFormat />
            <IconsM.LtextFormatRemove />
            <IconsM.LtextSize />
            <IconsM.Lbold />
            <IconsM.Litalic />
            <IconsM.Lunderline />
            <IconsM.Lstrikethrough />
            <IconsM.Lhighlight />
            <IconsM.LtextAlignLeft />
            <IconsM.LtextAlignCenter />
            <IconsM.LtextAlignRight />
            <IconsM.LtextAlignJustify />
            <IconsM.LlineSpacing />
            <IconsM.LindentIncrease />
            <IconsM.LindentDecrease />
            <IconsM.LtextWrap />
            <IconsM.Lpilcrow />
            <IconsM.LdirectionLtr />
            <IconsM.LdirectionRtl />
            <IconsM.LpageBreak />
            <IconsM.LpageBreak2 />
            <IconsM.LsortAlphaAsc />
            <IconsM.LsortAlphaDesc />
            <IconsM.LsortNumericAsc />
            <IconsM.LsortNumericDesc />
            <IconsM.LsortAmountAsc />
            <IconsM.LsortAmountDesc />
            <IconsM.LsortTimeAsc />
            <IconsM.LsortTimeDesc />
            <IconsM.Lsigma />
            <IconsM.LpencilLine />
            <IconsM.Lhand />
            <IconsM.Lhand2 />
            <IconsM.Lhand3 />
            <IconsM.Lhand4 />
            <IconsM.Lhand5 />
            <IconsM.Lhand6 />
            <IconsM.Lhand7 />
            <IconsM.Lhand8 />
            <IconsM.Lhand9 />
            <IconsM.Lhand10 />
            <IconsM.Lhand11 />
            <IconsM.Lhand12 />
            <IconsM.Lhand13 />
            <IconsM.Lhand14 />
            <IconsM.Lhand15 />
            <IconsM.Lhand16 />
            <IconsM.Lpointer />
            <IconsM.Lpointer2 />
            <IconsM.Lpointer3 />
            <IconsM.Lpointer4 />
            <IconsM.Lpointer5 />
            <IconsM.Lpointer6 />
            <IconsM.Lpointer7 />
            <IconsM.Lpointer8 />
            <IconsM.Lpointer9 />
            <IconsM.Lpointer10 />
            <IconsM.Lpointer11 />
            <IconsM.Lpointer12 />
            <IconsM.Lpointer13 />
            <IconsM.Lpointer14 />
            <IconsM.Lpointer15 />
            <IconsM.LborderStyle />
            <IconsM.LborderAll />
            <IconsM.LborderOuter />
            <IconsM.LborderInner />
            <IconsM.LborderTop />
            <IconsM.LborderHorizontal />
            <IconsM.LborderBottm />
            <IconsM.LborderLeft />
            <IconsM.LborderVertical />
            <IconsM.LborderRight />
            <IconsM.LborderNone />
            <IconsM.Lellipsis />
            <IconsM.Google />
            <IconsM.Google2 />
            <IconsM.Google3 />
            <IconsM.GooglePlus />
            <IconsM.GooglePlus2 />
            <IconsM.GooglePlus3 />
            <IconsM.Facebook />
            <IconsM.Facebook2 />
            <IconsM.Instagram />
            <IconsM.Twitter />
            <IconsM.R3dRotation />
            <IconsM.AcUnit />
            <IconsM.Alarm />
            <IconsM.AccessAlarms />
            <IconsM.Schedule />
            <IconsM.Accessibility />
            <IconsM.Accessible />
            <IconsM.AccountBalance />
            <IconsM.AccountBalanceWallet />
            <IconsM.AccountBox />
            <IconsM.AccountCircle />
            <IconsM.Adb />
            <IconsM.Add />
            <IconsM.AddAPhoto />
            <IconsM.AlarmAdd />
            <IconsM.AddAlert />
            <IconsM.AddBox />
            <IconsM.AddCircle />
            <IconsM.ControlPoint />
            <IconsM.AddLocation />
            <IconsM.AddShoppingCart />
            <IconsM.Queue />
            <IconsM.AddToQueue />
            <IconsM.Adjust />
            <IconsM.AirlineSeatFlat />
            <IconsM.AirlineSeatFlatAngled />
            <IconsM.AirlineSeatIndividualSuite />
            <IconsM.AirlineSeatLegroomExtra />
            <IconsM.AirlineSeatLegroomNormal />
            <IconsM.AirlineSeatLegroomReduced />
            <IconsM.AirlineSeatReclineExtra />
            <IconsM.AirlineSeatReclineNormal />
            <IconsM.Flight />
            <IconsM.AirplanemodeInactive />
            <IconsM.Airplay />
            <IconsM.AirportShuttle />
            <IconsM.AlarmOff />
            <IconsM.AlarmOn />
            <IconsM.Album />
            <IconsM.AllInclusive />
            <IconsM.AllOut />
            <IconsM.Android />
            <IconsM.Announcement />
            <IconsM.Apps />
            <IconsM.Archive />
            <IconsM.ArrowBack />
            <IconsM.ArrowDownward />
            <IconsM.ArrowDropDown />
            <IconsM.ArrowDropDownCircle />
            <IconsM.ArrowDropUp />
            <IconsM.ArrowForward />
            <IconsM.ArrowUpward />
            <IconsM.ArtTrack />
            <IconsM.AspectRatio />
            <IconsM.Poll />
            <IconsM.Assignment />
            <IconsM.AssignmentInd />
            <IconsM.AssignmentLate />
            <IconsM.AssignmentReturn />
            <IconsM.AssignmentReturned />
            <IconsM.AssignmentTurnedIn />
            <IconsM.Assistant />
            <IconsM.Flag />
            <IconsM.AttachFile />
            <IconsM.AttachMoney />
            <IconsM.Attachment />
            <IconsM.Audiotrack />
            <IconsM.Autorenew />
            <IconsM.AvTimer />
            <IconsM.Backspace />
            <IconsM.CloudUpload />
            <IconsM.BatteryAlert />
            <IconsM.BatteryChargingFull />
            <IconsM.BatteryStd />
            <IconsM.BatteryUnknown />
            <IconsM.BeachAccess />
            <IconsM.Beenhere />
            <IconsM.Block />
            <IconsM.Bluetooth />
            <IconsM.BluetoothSearching />
            <IconsM.BluetoothConnected />
            <IconsM.BluetoothDisabled />
            <IconsM.BlurCircular />
            <IconsM.BlurLinear />
            <IconsM.BlurOff />
            <IconsM.BlurOn />
            <IconsM.Class />
            <IconsM.TurnedIn />
            <IconsM.TurnedInNot />
            <IconsM.BorderAll />
            <IconsM.BorderBottom />
            <IconsM.BorderClear />
            <IconsM.BorderColor />
            <IconsM.BorderHorizontal />
            <IconsM.BorderInner />
            <IconsM.BorderLeft />
            <IconsM.BorderOuter />
            <IconsM.BorderRight />
            <IconsM.BorderStyle />
            <IconsM.BorderTop />
            <IconsM.BorderVertical />
            <IconsM.BrandingWatermark />
            <IconsM.Brightness1 />
            <IconsM.Brightness2 />
            <IconsM.Brightness3 />
            <IconsM.Brightness4 />
            <IconsM.BrightnessLow />
            <IconsM.BrightnessMedium />
            <IconsM.BrightnessHigh />
            <IconsM.BrightnessAuto />
            <IconsM.BrokenImage />
            <IconsM.Brush />
            <IconsM.BubbleChart />
            <IconsM.BugReport />
            <IconsM.Build />
            <IconsM.BurstMode />
            <IconsM.Domain />
            <IconsM.BusinessCenter />
            <IconsM.Cached />
            <IconsM.Cake />
            <IconsM.Phone />
            <IconsM.CallEnd />
            <IconsM.CallMade />
            <IconsM.MergeType />
            <IconsM.CallMissed />
            <IconsM.CallMissedOutgoing />
            <IconsM.CallReceived />
            <IconsM.CallSplit />
            <IconsM.CallToAction />
            <IconsM.Camera />
            <IconsM.PhotoCamera />
            <IconsM.CameraEnhance />
            <IconsM.CameraFront />
            <IconsM.CameraRear />
            <IconsM.CameraRoll />
            <IconsM.Cancel />
            <IconsM.Redeem />
            <IconsM.CardMembership />
            <IconsM.CardTravel />
            <IconsM.Casino />
            <IconsM.Cast />
            <IconsM.CastConnected />
            <IconsM.CenterFocusStrong />
            <IconsM.CenterFocusWeak />
            <IconsM.ChangeHistory />
            <IconsM.Chat />
            <IconsM.ChatBubble />
            <IconsM.ChatBubbleOutline />
            <IconsM.Check />
            <IconsM.CheckBox />
            <IconsM.CheckBoxOutlineBlank />
            <IconsM.CheckCircle />
            <IconsM.NavigateBefore />
            <IconsM.NavigateNext />
            <IconsM.ChildCare />
            <IconsM.ChildFriendly />
            <IconsM.ChromeReaderMode />
            <IconsM.Close />
            <IconsM.ClearAll />
            <IconsM.ClosedCaption />
            <IconsM.WbCloudy />
            <IconsM.CloudCircle />
            <IconsM.CloudDone />
            <IconsM.CloudDownload />
            <IconsM.CloudOff />
            <IconsM.CloudQueue />
            <IconsM.Code />
            <IconsM.PhotoLibrary />
            <IconsM.CollectionsBookmark />
            <IconsM.Palette />
            <IconsM.Colorize />
            <IconsM.Comment />
            <IconsM.Compare />
            <IconsM.CompareArrows />
            <IconsM.Laptop />
            <IconsM.ConfirmationNumber />
            <IconsM.ContactMail />
            <IconsM.ContactPhone />
            <IconsM.Contacts />
            <IconsM.ContentCopy />
            <IconsM.ContentCut />
            <IconsM.ContentPaste />
            <IconsM.ControlPointDuplicate />
            <IconsM.Copyright2 />
            <IconsM.ModeEdit />
            <IconsM.CreateNewFolder />
            <IconsM.Payment />
            <IconsM.Crop />
            <IconsM.Crop169 />
            <IconsM.Crop32 />
            <IconsM.CropLandscape />
            <IconsM.Crop75 />
            <IconsM.CropDin />
            <IconsM.CropFree />
            <IconsM.CropOriginal />
            <IconsM.CropPortrait />
            <IconsM.CropRotate />
            <IconsM.CropSquare />
            <IconsM.Dashboard />
            <IconsM.DataUsage />
            <IconsM.DateRange />
            <IconsM.Dehaze />
            <IconsM.Delete />
            <IconsM.DeleteForever />
            <IconsM.DeleteSweep />
            <IconsM.Description />
            <IconsM.DesktopMac />
            <IconsM.DesktopWindows />
            <IconsM.Details />
            <IconsM.DeveloperBoard />
            <IconsM.DeveloperMode />
            <IconsM.DeviceHub />
            <IconsM.Phonelink />
            <IconsM.DevicesOther />
            <IconsM.DialerSip />
            <IconsM.Dialpad />
            <IconsM.Directions />
            <IconsM.DirectionsBike />
            <IconsM.DirectionsBoat />
            <IconsM.DirectionsBus />
            <IconsM.DirectionsCar />
            <IconsM.DirectionsRailway />
            <IconsM.DirectionsRun />
            <IconsM.DirectionsTransit />
            <IconsM.DirectionsWalk />
            <IconsM.DiscFull />
            <IconsM.Dns />
            <IconsM.NotInterested />
            <IconsM.DoNotDisturbAlt />
            <IconsM.DoNotDisturbOff />
            <IconsM.RemoveCircle />
            <IconsM.Dock />
            <IconsM.Done />
            <IconsM.DoneAll />
            <IconsM.DonutLarge />
            <IconsM.DonutSmall />
            <IconsM.Drafts />
            <IconsM.DragHandle />
            <IconsM.TimeToLeave />
            <IconsM.Dvr />
            <IconsM.EditLocation />
            <IconsM.Eject />
            <IconsM.Markunread />
            <IconsM.EnhancedEncryption />
            <IconsM.Equalizer />
            <IconsM.Error />
            <IconsM.ErrorOutline />
            <IconsM.EuroSymbol />
            <IconsM.EvStation />
            <IconsM.InsertInvitation />
            <IconsM.EventAvailable />
            <IconsM.EventBusy />
            <IconsM.EventNote />
            <IconsM.EventSeat />
            <IconsM.ExitToApp />
            <IconsM.ExpandLess />
            <IconsM.ExpandMore />
            <IconsM.Explicit />
            <IconsM.Explore />
            <IconsM.Exposure />
            <IconsM.ExposureNeg1 />
            <IconsM.ExposureNeg2 />
            <IconsM.ExposurePlus1 />
            <IconsM.ExposurePlus2 />
            <IconsM.ExposureZero />
            <IconsM.Extension />
            <IconsM.Face />
            <IconsM.FastForward />
            <IconsM.FastRewind />
            <IconsM.Favorite />
            <IconsM.FavoriteBorder />
            <IconsM.FeaturedPlayList />
            <IconsM.FeaturedVideo />
            <IconsM.SmsFailed />
            <IconsM.FiberDvr />
            <IconsM.FiberManualRecord />
            <IconsM.FiberNew />
            <IconsM.FiberPin />
            <IconsM.FiberSmartRecord />
            <IconsM.GetApp />
            <IconsM.FileUpload />
            <IconsM.Filter />
            <IconsM.Filter1 />
            <IconsM.Filter2 />
            <IconsM.Filter3 />
            <IconsM.Filter4 />
            <IconsM.Filter5 />
            <IconsM.Filter6 />
            <IconsM.Filter7 />
            <IconsM.Filter8 />
            <IconsM.Filter9 />
            <IconsM.Filter9Plus />
            <IconsM.FilterBAndW />
            <IconsM.FilterCenterFocus />
            <IconsM.FilterDrama />
            <IconsM.FilterFrames />
            <IconsM.Terrain />
            <IconsM.FilterList />
            <IconsM.FilterNone />
            <IconsM.FilterTiltShift />
            <IconsM.FilterVintage />
            <IconsM.FindInPage />
            <IconsM.FindReplace />
            <IconsM.Fingerprint />
            <IconsM.FirstPage />
            <IconsM.FitnessCenter />
            <IconsM.Flare />
            <IconsM.FlashAuto />
            <IconsM.FlashOff />
            <IconsM.FlashOn />
            <IconsM.FlightLand />
            <IconsM.FlightTakeoff />
            <IconsM.Flip />
            <IconsM.FlipToBack />
            <IconsM.FlipToFront />
            <IconsM.Folder />
            <IconsM.FolderOpen />
            <IconsM.FolderShared />
            <IconsM.FolderSpecial />
            <IconsM.FontDownload />
            <IconsM.FormatAlignCenter />
            <IconsM.FormatAlignJustify />
            <IconsM.FormatAlignLeft />
            <IconsM.FormatAlignRight />
            <IconsM.FormatBold />
            <IconsM.FormatClear />
            <IconsM.FormatColorFill />
            <IconsM.FormatColorReset />
            <IconsM.FormatColorText />
            <IconsM.FormatIndentDecrease />
            <IconsM.FormatIndentIncrease />
            <IconsM.FormatItalic />
            <IconsM.FormatLineSpacing />
            <IconsM.FormatListBulleted />
            <IconsM.FormatListNumbered />
            <IconsM.FormatPaint />
            <IconsM.FormatQuote />
            <IconsM.FormatShapes />
            <IconsM.FormatSize />
            <IconsM.FormatStrikethrough />
            <IconsM.FormatTextdirectionLToR />
            <IconsM.FormatTextdirectionRToL />
            <IconsM.FormatUnderlined />
            <IconsM.QuestionAnswer />
            <IconsM.Forward />
            <IconsM.Forward10 />
            <IconsM.Forward30 />
            <IconsM.Forward5 />
            <IconsM.FreeBreakfast />
            <IconsM.Fullscreen />
            <IconsM.FullscreenExit />
            <IconsM.Functions />
            <IconsM.GTranslate />
            <IconsM.Games />
            <IconsM.Gavel />
            <IconsM.Gesture />
            <IconsM.Gif />
            <IconsM.Goat />
            <IconsM.GolfCourse />
            <IconsM.MyLocation />
            <IconsM.LocationSearching />
            <IconsM.LocationDisabled />
            <IconsM.Star />
            <IconsM.Gradient />
            <IconsM.Grain />
            <IconsM.GraphicEq />
            <IconsM.GridOff />
            <IconsM.GridOn />
            <IconsM.People />
            <IconsM.GroupAdd />
            <IconsM.GroupWork />
            <IconsM.Hd />
            <IconsM.HdrOff />
            <IconsM.HdrOn />
            <IconsM.HdrStrong />
            <IconsM.HdrWeak />
            <IconsM.Headset />
            <IconsM.HeadsetMic />
            <IconsM.Healing />
            <IconsM.Hearing />
            <IconsM.Help />
            <IconsM.HelpOutline />
            <IconsM.HighQuality />
            <IconsM.Highlight />
            <IconsM.HighlightOff />
            <IconsM.Restore />
            <IconsM.Home />
            <IconsM.HotTub />
            <IconsM.LocalHotel />
            <IconsM.HourglassEmpty />
            <IconsM.HourglassFull />
            <IconsM.Http />
            <IconsM.Lock />
            <IconsM.Photo />
            <IconsM.ImageAspectRatio />
            <IconsM.ImportContacts />
            <IconsM.ImportExport />
            <IconsM.ImportantDevices />
            <IconsM.Inbox />
            <IconsM.IndeterminateCheckBox />
            <IconsM.Info />
            <IconsM.InfoOutline />
            <IconsM.Input />
            <IconsM.InsertComment />
            <IconsM.InsertDriveFile />
            <IconsM.TagFaces />
            <IconsM.Link />
            <IconsM.InvertColors />
            <IconsM.InvertColorsOff />
            <IconsM.Iso />
            <IconsM.Keyboard />
            <IconsM.KeyboardArrowDown />
            <IconsM.KeyboardArrowLeft />
            <IconsM.KeyboardArrowRight />
            <IconsM.KeyboardArrowUp />
            <IconsM.KeyboardBackspace />
            <IconsM.KeyboardCapslock />
            <IconsM.KeyboardHide />
            <IconsM.KeyboardReturn />
            <IconsM.KeyboardTab />
            <IconsM.KeyboardVoice />
            <IconsM.Kitchen />
            <IconsM.Label />
            <IconsM.LabelOutline />
            <IconsM.Language />
            <IconsM.LaptopChromebook />
            <IconsM.LaptopMac />
            <IconsM.LaptopWindows />
            <IconsM.LastPage />
            <IconsM.OpenInNew />
            <IconsM.Layers />
            <IconsM.LayersClear />
            <IconsM.LeakAdd />
            <IconsM.LeakRemove />
            <IconsM.Lens />
            <IconsM.LibraryBooks />
            <IconsM.LibraryMusic />
            <IconsM.LightbulbOutline />
            <IconsM.LineStyle />
            <IconsM.LineWeight />
            <IconsM.LinearScale />
            <IconsM.LinkedCamera />
            <IconsM.List />
            <IconsM.LiveHelp />
            <IconsM.LiveTv />
            <IconsM.LocalPlay />
            <IconsM.LocalAirport />
            <IconsM.LocalAtm />
            <IconsM.LocalBar />
            <IconsM.LocalCafe />
            <IconsM.LocalCarWash />
            <IconsM.LocalConvenienceStore />
            <IconsM.RestaurantMenu />
            <IconsM.LocalDrink />
            <IconsM.LocalFlorist />
            <IconsM.LocalGasStation />
            <IconsM.ShoppingCart />
            <IconsM.LocalHospital />
            <IconsM.LocalLaundryService />
            <IconsM.LocalLibrary />
            <IconsM.LocalMall />
            <IconsM.Theaters />
            <IconsM.LocalOffer />
            <IconsM.LocalParking />
            <IconsM.LocalPharmacy />
            <IconsM.LocalPizza />
            <IconsM.Print />
            <IconsM.LocalShipping />
            <IconsM.LocalTaxi />
            <IconsM.LocationCity />
            <IconsM.LocationOff />
            <IconsM.Room />
            <IconsM.LockOpen />
            <IconsM.LockOutline />
            <IconsM.Looks />
            <IconsM.Looks3 />
            <IconsM.Looks4 />
            <IconsM.Looks5 />
            <IconsM.Looks6 />
            <IconsM.LooksOne />
            <IconsM.LooksTwo />
            <IconsM.Sync />
            <IconsM.Loupe />
            <IconsM.LowPriority />
            <IconsM.Loyalty />
            <IconsM.MailOutline />
            <IconsM.Map />
            <IconsM.MarkunreadMailbox />
            <IconsM.Memory />
            <IconsM.Menu />
            <IconsM.Message />
            <IconsM.Mic />
            <IconsM.MicNone />
            <IconsM.MicOff />
            <IconsM.Mms />
            <IconsM.ModeComment />
            <IconsM.MonetizationOn />
            <IconsM.MoneyOff />
            <IconsM.MonochromePhotos />
            <IconsM.MoodBad />
            <IconsM.More />
            <IconsM.MoreHoriz />
            <IconsM.MoreVert />
            <IconsM.Motorcycle />
            <IconsM.Mouse />
            <IconsM.MoveToInbox />
            <IconsM.MovieCreation />
            <IconsM.MovieFilter />
            <IconsM.MultilineChart />
            <IconsM.MusicNote />
            <IconsM.MusicVideo />
            <IconsM.Nature />
            <IconsM.NaturePeople />
            <IconsM.Navigation />
            <IconsM.NearMe />
            <IconsM.NetworkCell />
            <IconsM.NetworkCheck />
            <IconsM.NetworkLocked />
            <IconsM.NetworkWifi />
            <IconsM.NewReleases />
            <IconsM.NextWeek />
            <IconsM.Nfc />
            <IconsM.NoEncryption />
            <IconsM.SignalCellularNoSim />
            <IconsM.Note />
            <IconsM.NoteAdd />
            <IconsM.Notifications />
            <IconsM.NotificationsActive />
            <IconsM.NotificationsNone />
            <IconsM.NotificationsOff />
            <IconsM.NotificationsPaused />
            <IconsM.OfflinePin />
            <IconsM.OndemandVideo />
            <IconsM.Opacity />
            <IconsM.OpenInBrowser />
            <IconsM.OpenWith />
            <IconsM.Pages />
            <IconsM.Pageview />
            <IconsM.PanTool />
            <IconsM.Panorama />
            <IconsM.RadioButtonUnchecked />
            <IconsM.PanoramaHorizontal />
            <IconsM.PanoramaVertical />
            <IconsM.PanoramaWideAngle />
            <IconsM.PartyMode />
            <IconsM.Pause />
            <IconsM.PauseCircleFilled />
            <IconsM.PauseCircleOutline />
            <IconsM.PeopleOutline />
            <IconsM.PermCameraMic />
            <IconsM.PermContactCalendar />
            <IconsM.PermDataSetting />
            <IconsM.PermDeviceInformation />
            <IconsM.PersonOutline />
            <IconsM.PermMedia />
            <IconsM.PermPhoneMsg />
            <IconsM.PermScanWifi />
            <IconsM.Person />
            <IconsM.PersonAdd />
            <IconsM.PersonPin />
            <IconsM.PersonPinCircle />
            <IconsM.PersonalVideo />
            <IconsM.Pets />
            <IconsM.PhoneAndroid />
            <IconsM.PhoneBluetoothSpeaker />
            <IconsM.PhoneForwarded />
            <IconsM.PhoneInTalk />
            <IconsM.PhoneIphone />
            <IconsM.PhoneLocked />
            <IconsM.PhoneMissed />
            <IconsM.PhonePaused />
            <IconsM.PhonelinkErase />
            <IconsM.PhonelinkLock />
            <IconsM.PhonelinkOff />
            <IconsM.PhonelinkRing />
            <IconsM.PhonelinkSetup />
            <IconsM.PhotoAlbum />
            <IconsM.PhotoFilter />
            <IconsM.PhotoSizeSelectActual />
            <IconsM.PhotoSizeSelectLarge />
            <IconsM.PhotoSizeSelectSmall />
            <IconsM.PictureAsPdf />
            <IconsM.PictureInPicture />
            <IconsM.PictureInPictureAlt />
            <IconsM.PieChart />
            <IconsM.PieChartOutlined />
            <IconsM.PinDrop />
            <IconsM.PlayArrow />
            <IconsM.PlayCircleFilled />
            <IconsM.PlayCircleOutline />
            <IconsM.PlayForWork />
            <IconsM.PlaylistAdd />
            <IconsM.PlaylistAddCheck />
            <IconsM.PlaylistPlay />
            <IconsM.PlusOne />
            <IconsM.Polymer />
            <IconsM.Pool />
            <IconsM.PortableWifiOff />
            <IconsM.Portrait />
            <IconsM.Power />
            <IconsM.PowerInput />
            <IconsM.PowerSettingsNew />
            <IconsM.PregnantWoman />
            <IconsM.PresentToAll />
            <IconsM.PriorityHigh />
            <IconsM.Public />
            <IconsM.Publish />
            <IconsM.QueueMusic />
            <IconsM.QueuePlayNext />
            <IconsM.Radio />
            <IconsM.RadioButtonChecked />
            <IconsM.RateReview />
            <IconsM.Receipt />
            <IconsM.RecentActors />
            <IconsM.RecordVoiceOver />
            <IconsM.Redo />
            <IconsM.Refresh />
            <IconsM.Remove />
            <IconsM.RemoveCircleOutline />
            <IconsM.RemoveFromQueue />
            <IconsM.Visibility />
            <IconsM.RemoveShoppingCart />
            <IconsM.Reorder />
            <IconsM.Repeat />
            <IconsM.RepeatOne />
            <IconsM.Replay />
            <IconsM.Replay10 />
            <IconsM.Replay30 />
            <IconsM.Replay5 />
            <IconsM.Reply />
            <IconsM.ReplyAll />
            <IconsM.Report />
            <IconsM.Warning />
            <IconsM.Restaurant />
            <IconsM.RestorePage />
            <IconsM.RingVolume />
            <IconsM.RoomService />
            <IconsM.Rotate90DegreesCcw />
            <IconsM.RotateLeft />
            <IconsM.RotateRight />
            <IconsM.RoundedCorner />
            <IconsM.Router />
            <IconsM.Rowing />
            <IconsM.RssFeed />
            <IconsM.RvHookup />
            <IconsM.Satellite />
            <IconsM.Save />
            <IconsM.Scanner />
            <IconsM.School />
            <IconsM.ScreenLockLandscape />
            <IconsM.ScreenLockPortrait />
            <IconsM.ScreenLockRotation />
            <IconsM.ScreenRotation />
            <IconsM.ScreenShare />
            <IconsM.SdStorage />
            <IconsM.Search />
            <IconsM.Security />
            <IconsM.SelectAll />
            <IconsM.Send />
            <IconsM.SentimentDissatisfied />
            <IconsM.SentimentNeutral />
            <IconsM.SentimentSatisfied />
            <IconsM.SentimentVeryDissatisfied />
            <IconsM.SentimentVerySatisfied />
            <IconsM.Settings />
            <IconsM.SettingsApplications />
            <IconsM.SettingsBackupRestore />
            <IconsM.SettingsBluetooth />
            <IconsM.SettingsBrightness />
            <IconsM.SettingsCell />
            <IconsM.SettingsEthernet />
            <IconsM.SettingsInputAntenna />
            <IconsM.SettingsInputComposite />
            <IconsM.SettingsInputHdmi />
            <IconsM.SettingsInputSvideo />
            <IconsM.SettingsOverscan />
            <IconsM.SettingsPhone />
            <IconsM.SettingsPower />
            <IconsM.SettingsRemote />
            <IconsM.SettingsSystemDaydream />
            <IconsM.SettingsVoice />
            <IconsM.Share />
            <IconsM.Shop />
            <IconsM.ShopTwo />
            <IconsM.ShoppingBasket />
            <IconsM.ShortText />
            <IconsM.ShowChart />
            <IconsM.Shuffle />
            <IconsM.SignalCellular4Bar />
            <IconsM.SignalCellularConnectedNoInternet4Bar />
            <IconsM.SignalCellularNull />
            <IconsM.SignalCellularOff />
            <IconsM.SignalWifi4Bar />
            <IconsM.SignalWifi4BarLock />
            <IconsM.SignalWifiOff />
            <IconsM.SimCard />
            <IconsM.SimCardAlert />
            <IconsM.SkipNext />
            <IconsM.SkipPrevious />
            <IconsM.Slideshow />
            <IconsM.SlowMotionVideo />
            <IconsM.StayPrimaryPortrait />
            <IconsM.SmokeFree />
            <IconsM.SmokingRooms />
            <IconsM.Textsms />
            <IconsM.Snooze />
            <IconsM.Sort />
            <IconsM.SortByAlpha />
            <IconsM.Spa />
            <IconsM.SpaceBar />
            <IconsM.Speaker />
            <IconsM.SpeakerGroup />
            <IconsM.SpeakerNotes />
            <IconsM.SpeakerNotesOff />
            <IconsM.SpeakerPhone />
            <IconsM.Spellcheck />
            <IconsM.StarBorder />
            <IconsM.StarHalf />
            <IconsM.Stars />
            <IconsM.StayPrimaryLandscape />
            <IconsM.Stop />
            <IconsM.StopScreenShare />
            <IconsM.Storage />
            <IconsM.StoreMallDirectory />
            <IconsM.Straighten />
            <IconsM.Streetview />
            <IconsM.StrikethroughS />
            <IconsM.Style />
            <IconsM.SubdirectoryArrowLeft />
            <IconsM.SubdirectoryArrowRight />
            <IconsM.Subject />
            <IconsM.Subscriptions />
            <IconsM.Subtitles />
            <IconsM.Subway />
            <IconsM.SupervisorAccount />
            <IconsM.SurroundSound />
            <IconsM.SwapCalls />
            <IconsM.SwapHoriz />
            <IconsM.SwapVert />
            <IconsM.SwapVerticalCircle />
            <IconsM.SwitchCamera />
            <IconsM.SwitchVideo />
            <IconsM.SyncDisabled />
            <IconsM.SyncProblem />
            <IconsM.SystemUpdate />
            <IconsM.SystemUpdateAlt />
            <IconsM.Tab />
            <IconsM.TabUnselected />
            <IconsM.Tablet />
            <IconsM.TabletAndroid />
            <IconsM.TabletMac />
            <IconsM.TapAndPlay />
            <IconsM.TextFields />
            <IconsM.TextFormat />
            <IconsM.Texture />
            <IconsM.ThumbDown />
            <IconsM.ThumbUp />
            <IconsM.ThumbsUpDown />
            <IconsM.Timelapse />
            <IconsM.Timeline />
            <IconsM.Timer />
            <IconsM.Timer10 />
            <IconsM.Timer3 />
            <IconsM.TimerOff />
            <IconsM.Title />
            <IconsM.Toc />
            <IconsM.Today />
            <IconsM.Toll />
            <IconsM.Tonality />
            <IconsM.TouchApp />
            <IconsM.Toys />
            <IconsM.TrackChanges />
            <IconsM.Traffic />
            <IconsM.Train />
            <IconsM.Tram />
            <IconsM.TransferWithinAStation />
            <IconsM.Transform />
            <IconsM.Translate />
            <IconsM.TrendingDown />
            <IconsM.TrendingFlat />
            <IconsM.TrendingUp />
            <IconsM.Tune />
            <IconsM.Tv />
            <IconsM.Unarchive />
            <IconsM.Undo />
            <IconsM.UnfoldLess />
            <IconsM.UnfoldMore />
            <IconsM.Update />
            <IconsM.Usb />
            <IconsM.VerifiedUser />
            <IconsM.VerticalAlignBottom />
            <IconsM.VerticalAlignCenter />
            <IconsM.VerticalAlignTop />
            <IconsM.Vibration />
            <IconsM.VideoCall />
            <IconsM.VideoLabel />
            <IconsM.VideoLibrary />
            <IconsM.Videocam />
            <IconsM.VideocamOff />
            <IconsM.VideogameAsset />
            <IconsM.ViewAgenda />
            <IconsM.ViewArray />
            <IconsM.ViewCarousel />
            <IconsM.ViewColumn />
            <IconsM.ViewComfy />
            <IconsM.ViewCompact />
            <IconsM.ViewDay />
            <IconsM.ViewHeadline />
            <IconsM.ViewList />
            <IconsM.ViewModule />
            <IconsM.ViewQuilt />
            <IconsM.ViewStream />
            <IconsM.ViewWeek />
            <IconsM.Vignette />
            <IconsM.VisibilityOff />
            <IconsM.VoiceChat />
            <IconsM.Voicemail />
            <IconsM.VolumeDown />
            <IconsM.VolumeMute />
            <IconsM.VolumeOff />
            <IconsM.VolumeUp />
            <IconsM.VpnKey />
            <IconsM.VpnLock />
            <IconsM.Wallpaper />
            <IconsM.Watch />
            <IconsM.WatchLater />
            <IconsM.WbAuto />
            <IconsM.WbIncandescent />
            <IconsM.WbIridescent />
            <IconsM.WbSunny />
            <IconsM.Wc />
            <IconsM.Web />
            <IconsM.WebAsset />
            <IconsM.Weekend />
            <IconsM.Whatshot />
            <IconsM.Widgets />
            <IconsM.Wifi />
            <IconsM.WifiLock />
            <IconsM.WifiTethering />
            <IconsM.Work />
            <IconsM.WrapText />
            <IconsM.YoutubeSearchedFor />
            <IconsM.ZoomIn />
            <IconsM.ZoomOut />
            <IconsM.ZoomOutMap />


        </div>
    ), { info: 'Utilisation du composant en lui passant les données à afficher' }
)
    .add('IconLoading',
        () => (
            <div style={{ padding: "16px" }} >
                <Icons.IconLoading AlertNumber={9} />
                <br /><br />
                <Icons.IconLoading IconSize="7" />
                <br /><br />
                <Icons.IconLoading BackgroundColor="blue" Color="red" IconSize="20" AlertNumber={4} AlertCircle={{ Active: true, Color: "red" }} />
                <br /><br />
                <Icons.IconLoading onClick={() => alert("bonjour")} > click me !</Icons.IconLoading>
                <br /><br />
                <Icons.IconLoading AvecCercle={true} > With circle</Icons.IconLoading>
                <br /><br />
                <Icons.IconLoading IconSize="60em" > 60em</Icons.IconLoading>
                <br /><br />
                <Icons.IconLoading IconSize="1in" > 1in</Icons.IconLoading>
                <br /><br />
                <Icons.IconLoading IconSize="8cm" BackgroundColor="grey" > 8cm</Icons.IconLoading>
            </div>
        ), { info: 'Utilisation du composant en lui passant les données à afficher' }
    )
    .add('IconAlertes',
        () => (
            <div>
                <Icons.IconAlertes />
                <br /><br />
                <Icons.IconAlertes IconSize="7px" />
                <br /><br />
                <Icons.IconAlertes BackgroundColor="gray" Color="red" IconSize="20px" />
                <br /><br />
                <Icons.IconAlertes BackgroundColor="gray" Color="red" IconSize="40px" />

                <br /><br />
                <Icons.IconAlertes AlertNumber={3} />
                <br /><br />
                <Icons.IconAlertes AlertNumber={36} IconSize="7px" />
                <br /><br />
                <Icons.IconAlertes AlertNumber={36} BackgroundColor="gray" Color="red" IconSize="20px" />
                <br /><br />
                <Icons.IconAlertes AlertNumber={36} BackgroundColor="gray" Color="red" IconSize="40px" />

                <br /><br />
                <Icons.IconAlertes AlertNumber={3} AlertCircle={{ Active: true, Color: "#f44336" }} />
                <br /><br />
                <Icons.IconAlertes AlertNumber={36} AlertCircle={{ Active: true, Color: "#f44336" }} IconSize="7px" />
                <br /><br />
                <Icons.IconAlertes AlertNumber={36} AlertCircle={{ Active: true, Color: "#f44336" }} BackgroundColor="gray" Color="red" IconSize="20px" />
                <br /><br />
                <Icons.IconAlertes AlertNumber={36} AlertCircle={{ Active: true, Color: "#f44336" }} BackgroundColor="gray" Color="red" IconSize="40px" />

                <br /><br />
                <Icons.IconAlertes AlertNumber={3} AlertCircle={{ Active: true, Color: "#f44336" }} AlertFont={alertFont} />
                <br /><br />
                <Icons.IconAlertes AlertNumber={36} AlertCircle={{ Active: true, Color: "#f44336" }} AlertFont={alertFont} IconSize="7px" />
                <br /><br />
                <Icons.IconAlertes AlertNumber={36} AlertCircle={{ Active: true, Color: "#f44336" }} AlertFont={alertFont} BackgroundColor="gray" Color="red" IconSize="20px" />
                <br /><br />
                <Icons.IconAlertes AlertNumber={36} AlertCircle={{ Active: true, Color: "#f44336" }} AlertFont={alertFont} BackgroundColor="gray" Color="red" IconSize="40px" />
            </div>
        ), { info: 'Utilisation du composant en lui passant les données à afficher' }
    )
    .add('Icone LSWA - Perceval',
        () => (
            <div style={{ padding: "16px" }} >
                <Icons.IconLswaLink IconSize="20" AlertNumber={3} AlertCircle={{ Active: true, Color: "red" }} />
                <br />
                <Icons.IconLswaLink IconSize="32" AlertNumber={3} AlertCircle={{ Active: true, Color: "red" }} />
                <br />
                <Icons.IconLswaLink IconSize="150" AlertNumber={3} AlertCircle={{ Active: true, Color: "red" }} />

                <br /><br />
                <Icons.IconPercevalLink IconSize="20" AlertNumber={3} AlertCircle={{ Active: true, Color: "red" }} />
                <br />
                <Icons.IconPercevalLink IconSize="32" AlertNumber={3} AlertCircle={{ Active: true, Color: "red" }} />
                <br />
                <Icons.IconPercevalLink IconSize="150" AlertNumber={3} AlertCircle={{ Active: true, Color: "red" }} />
            </div>
        ), { info: 'Utilisation du composant en lui passant les données à afficher' }
    ) 